server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/auth/ {
        proxy_pass http://auth-service:5001;
    }

    location /api/products/ {
        proxy_pass http://product-service:5002;
    }

    location /api/orders/ {
        proxy_pass http://order-service:5003;
    }
}